const Tokens = {
  ASSIGN: "=",
  END: "END",
  BEGIN: "BEGIN",
  COND: "cond",
  REPEAT: "repeat",
  ADD: "+",
  SUB: "-",
  MUL: "*",
  DIV: "/",
  MOD: "%",
  FLRDIV: "$",
  GT: ">",
  LT: "<",
  GTE: ">=",
  LTE: "<=",
  EQ: "==",
  NE: "!=",
  PARENTHESISOPEN: "(",
  PARENTHESISCLOSE: ")",
  CODEBLOCKOPEN: "{",
  CODEBLOCKCLOSE: "}",
};

export default Tokens;
